[package]
name = "PowderRS"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glium = "0.32.1"
rand = "0.8.5"

[profile.dev]
opt-level = 1
