unstable_features = true
edition = "2021"
hard_tabs = true
imports_granularity = "Module"
group_imports = "StdExternalCrate"
newline_style = "Unix"
normalize_comments = true
struct_field_align_threshold = 15
type_punctuation_density = "Compressed"
