unstable_features = true
edition = "2021"

hard_tabs = true
imports_granularity = "Module"
group_imports = "StdExternalCrate"
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
struct_field_align_threshold = 15
type_punctuation_density = "Compressed"
binop_separator = "Back"
blank_lines_upper_bound = 2
brace_style = "SameLineWhere"
combine_control_expr = false
control_brace_style = "ClosingNextLine"
hex_literal_case = "Upper"
overflow_delimited_expr = true
trailing_comma = "Never"
use_field_init_shorthand = true
use_try_shorthand = true
where_single_line = true

