name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
  
    runs-on: ${{ matrix.os }}

    steps:    
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1.0.6
      with:
          toolchain: nightly
          components: clippy
          default: true
          override: true
    - name: Build
      run: cargo build --verbose --release
    #- name: Run tests # currently there are no tests :P
    #  run: cargo test --verbose
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      if: ${{ matrix.os == 'ubuntu-latest' }}
      with:
        path: target/release/powder_rs
    - uses: actions/upload-artifact@v3.1.2
      if: ${{ matrix.os == 'windows-latest' }}
      with:
        path: target/release/powder_rs.exe
