name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        target: [ubuntu-latest, windows-latest]
  
    runs-on: ${{ matrix.os }}

    steps:    
    - uses: actions/checkout@v3
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1.0.6
      with:
          toolchain: nightly
          components: clippy
          default: true
          override: true
    - name: Build
      run: cargo build --verbose --release
    #- name: Run tests # currently there are no tests :P
    #  run: cargo test --verbose
